<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>AuthQueryService.Infrastructure</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AuthQueryService.Application\AuthQueryService.Application.csproj" />
	  <ProjectReference Include="..\AuthQueryService.Domain\AuthQueryService.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
		<PackageReference Include="MongoDB.Driver" Version="3.5.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
		<PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
	</ItemGroup>
</Project>
