<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PodcastService.Domain\PodcastService.Domain.csproj" />
    <ProjectReference Include="..\PodcastService.infrastucture\PodcastService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Queries\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
