<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>AuthQueryService.Application</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AuthQueryService.Domain\AuthQueryService.Domain.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
		<PackageReference Include="Scrutor" Version="6.0.1" />
	</ItemGroup>
</Project>
