<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="BackgroundJobs\" />
		<Folder Include="ExternalServices\AzuraCast\ApiModels\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LiveSessionService.Application\LiveSessionService.Application.csproj" />
		<ProjectReference Include="..\LiveSessionService.Domain\LiveSessionService.Domain.csproj" />
	</ItemGroup>

</Project>
