// <auto-generated />
using System;
using AiService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiDbContext))]
    partial class AiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiService.Domain.Entities.AiPrompt", b =>
                {
                    b.Property<Guid>("PromptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("context_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_text");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("temperature");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PromptId")
                        .HasName("ai_prompts_pkey");

                    b.ToTable("ai_prompts", (string)null);
                });

            modelBuilder.Entity("AiService.Domain.Entities.AiServiceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PromptTemplate")
                        .HasColumnType("text")
                        .HasColumnName("prompt_template");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("ai_service_configs_pkey");

                    b.HasIndex(new[] { "Provider", "IsActive" }, "ai_service_configs_provider_active_idx");

                    b.ToTable("ai_service_configs", (string)null);
                });

            modelBuilder.Entity("AiService.Domain.Entities.AiUsage", b =>
                {
                    b.Property<Guid>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usage_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<Guid?>("ScriptId")
                        .HasColumnType("uuid")
                        .HasColumnName("script_id");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UsageId")
                        .HasName("ai_usage_pkey");

                    b.HasIndex("ScriptId");

                    b.ToTable("ai_usage", (string)null);
                });

            modelBuilder.Entity("AiService.Domain.Entities.Script", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("script_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_text");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("context_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<Guid?>("ParentScriptId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_script_id");

                    b.Property<Guid?>("PromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.Property<string>("ScriptSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("script_source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ScriptId")
                        .HasName("scripts_pkey");

                    b.HasIndex("ParentScriptId");

                    b.HasIndex("PromptId");

                    b.HasIndex(new[] { "AuthorId", "ContextType" }, "scripts_author_context_idx");

                    b.HasIndex(new[] { "AuthorId" }, "scripts_author_id_idx");

                    b.ToTable("scripts", (string)null);
                });

            modelBuilder.Entity("AiService.Domain.Entities.ScriptAudio", b =>
                {
                    b.Property<Guid>("AudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audio_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audio_path");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<decimal?>("Pitch")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("pitch");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("uuid")
                        .HasColumnName("script_id");

                    b.Property<decimal?>("Speed")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("speed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("voice_id");

                    b.HasKey("AudioId")
                        .HasName("script_audios_pkey");

                    b.HasIndex("VoiceId");

                    b.HasIndex(new[] { "ScriptId" }, "script_audios_script_id_idx");

                    b.ToTable("script_audios", (string)null);
                });

            modelBuilder.Entity("AiService.Domain.Entities.TtsVoice", b =>
                {
                    b.Property<Guid>("VoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("voice_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("VoiceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voice_code");

                    b.HasKey("VoiceId")
                        .HasName("tts_voices_pkey");

                    b.HasIndex(new[] { "Provider", "VoiceCode" }, "tts_voices_provider_voice_code_key")
                        .IsUnique();

                    b.ToTable("tts_voices", (string)null);
                });

            modelBuilder.Entity("AiService.Domain.Entities.AiUsage", b =>
                {
                    b.HasOne("AiService.Domain.Entities.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("ai_usage_script_id_fkey");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("AiService.Domain.Entities.Script", b =>
                {
                    b.HasOne("AiService.Domain.Entities.Script", "ParentScript")
                        .WithMany("ChildScripts")
                        .HasForeignKey("ParentScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("scripts_parent_script_id_fkey");

                    b.HasOne("AiService.Domain.Entities.AiPrompt", "Prompt")
                        .WithMany("Scripts")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("scripts_prompt_id_fkey");

                    b.Navigation("ParentScript");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AiService.Domain.Entities.ScriptAudio", b =>
                {
                    b.HasOne("AiService.Domain.Entities.Script", "Script")
                        .WithMany("Audios")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("script_audios_script_id_fkey");

                    b.HasOne("AiService.Domain.Entities.TtsVoice", "Voice")
                        .WithMany("Audios")
                        .HasForeignKey("VoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("script_audios_voice_id_fkey");

                    b.Navigation("Script");

                    b.Navigation("Voice");
                });

            modelBuilder.Entity("AiService.Domain.Entities.AiPrompt", b =>
                {
                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("AiService.Domain.Entities.Script", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("ChildScripts");
                });

            modelBuilder.Entity("AiService.Domain.Entities.TtsVoice", b =>
                {
                    b.Navigation("Audios");
                });
#pragma warning restore 612, 618
        }
    }
}
